# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
compiler:
  solc:
    version: 0.8.10

reports:
  exclude_contracts:
    - SafeMath

# dependencies:
#     - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@3.4.2/contracts"
#     - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.2/contracts"
#     - uniswap/v2-core@1.0.1
# compiler:
#     solc:
#         remappings:
#             - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.2.1-solc-0.7"
#             - 'uniswap=uniswap/v2-core@1.0.1'
  
     